### PR TITLE
HUD draft, item placement bugfix

### PR DESCRIPTION
**Pull request by maxlebedev**
refactored boundary values to their own struct, added left and right hud bars, corrected camera code, solved item placement bug for real now

### CODE REVIEW

**Comment by SodaSyrup** [comment]
Initialized OpenGL with: 4.2 (Core Profile) Mesa 22.2.5, Shader Language Version: 4.20
[src/main.rs:127] "save don't exist, making new game" = "save don't exist, making new game"
selected unimplemented spells school 1
xdg_wm_base@16: error 4: xdg_surface buffer (2080 x 1032) does not match the configured maximized state (1920 x 1032)

**Comment by SodaSyrup** [comment]
When trying to maximize it crashed.

"Initialized OpenGL with: 4.2 (Core Profile) Mesa 22.2.5, Shader Language Version: 4.20
[src/main.rs:127] "save don't exist, making new game" = "save don't exist, making new game"
selected unimplemented spells school 1
xdg_wm_base@16: error 4: xdg_surface buffer (2080 x 1032) does not match the configured maximized state (1920 x 1032)"

**Review by SodaSyrup — COMMENTED** [review]
When trying to maximize it crashed.

"Initialized OpenGL with: 4.2 (Core Profile) Mesa 22.2.5, Shader Language Version: 4.20
[src/main.rs:127] "save don't exist, making new game" = "save don't exist, making new game"
selected unimplemented spells school 1
xdg_wm_base@16: error 4: xdg_surface buffer (2080 x 1032) does not match the configured maximized state (1920 x 1032)"

**Comment by maxlebedev** [comment]
> When trying to maximize it crashed.
> 
> "Initialized OpenGL with: 4.2 (Core Profile) Mesa 22.2.5, Shader Language Version: 4.20 [src/main.rs:127] "save don't exist, making new game" = "save don't exist, making new game" selected unimplemented spells school 1 xdg_wm_base@16: error 4: xdg_surface buffer (2080 x 1032) does not match the configured maximized state (1920 x 1032)"

Fixed

**Review by shengjie-ji — APPROVED** [review]
LGTM

**Pull request merged**
